name: printing_example
description: Pdf Printing Example

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  printing_plus:
  vector_math: ^2.1.0
  xml: ">=5.1.0 <7.0.0"

dependency_overrides:
  printing_plus:
    path: ../

dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true
